import Head from "next/head"
import Image from "next/image"
import Banner from "../components/Banner"
import Header from "../components/Header"
import Posts from "../components/Posts"
import { sanityClient, urlFor } from "../sanity"
export default function Home({ posts }) {
  console.log(posts)
  return (
    <div className="max-w-7xl mx-auto">
      <Head>
        <title>Medium Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />
      <Posts posts={posts} />
    </div>
  )
}
export async function getServerSideProps() {
  const query = `*[_type=="post"]{
    _id,
    title,
    author->{
      name,
      image
    }, 
    description,
    mainImage,
    slug
   }`

  const posts = await sanityClient.fetch(query)

  return {
    props: {
      posts: posts,
    },
  }
}
